### ISSUE TITLE
Error taking checkpoint

### ISSUE THREAD

**Issue by kdprince33** [microsoft/FASTER#135]
The following code results in an exception:

Guid token;

                    while (!_fasterCache.TakeFullCheckpoint(out token))
                    {
                       
                        _fasterCache.Refresh();
                    }
                    _fasterCache.CompleteCheckpoint(true); 

Error was: Invalid attempt made to decrement the event's count below zero.    at System.Threading.CountdownEvent.Signal()
   at FASTER.core.MallocFixedPageSize`1.AsyncFlushCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlap) in d:\a\1\s\cs\src\core\Allocator\MallocFixedPageSize.cs:line 524
   at FASTER.core.LocalStorageDevice.WriteAsync(IntPtr sourceAddress, Int32 segmentId, UInt64 destinationAddress, UInt32 numBytesToWrite, IOCompletionCallback callback, IAsyncResult asyncResult) in d:\a\1\s\cs\src\core\Device\LocalStorageDevice.cs:line 125
   at FASTER.core.StorageDeviceBase.WriteAsync(IntPtr alignedSourceAddress, UInt64 alignedDestinationAddress, UInt32 numBytesToWrite, IOCompletionCallback callback, IAsyncResult asyncResult) in d:\a\1\s\cs\src\core\Device\StorageDeviceBase.cs:line 92
   at FASTER.core.MallocFixedPageSize`1.BeginCheckpoint(IDevice device, UInt64 offset, UInt64& numBytesWritten) in d:\a\1\s\cs\src\core\Allocator\MallocFixedPageSize.cs:line 516
   at FASTER.core.FasterBase.TakeIndexFuzzyCheckpoint() in d:\a\1\s\cs\src\core\Index\FASTER\IndexCheckpoint.cs:line 34
   at FASTER.core.FasterKV`6.GlobalMoveToNextState(SystemState currentState, SystemState nextState, Int64& context) in d:\a\1\s\cs\src\core\Index\FASTER\Checkpoint.cs:line 210
   at FASTER.core.FasterKV`6.HandleCheckpointingPhases() in d:\a\1\s\cs\src\core\Index\FASTER\Checkpoint.cs:line 419
   at FASTER.core.FasterKV`6.InternalCompletePending(Boolean wait) in d:\a\1\s\cs\src\core\Index\FASTER\FASTERThread.cs:line 151
   at FASTER.core.FasterKV`6.CompleteCheckpoint(Boolean wait) in d:\a\1\s\cs\src\core\Index\FASTER\FASTER.cs:line 348

This does not happen 100% of the time, but does so often on the build server.

**Comment by badrishc** [comment]
Are you trying to take checkpoints from more than one thread?

**Comment by badrishc** [comment]
And are there operations happening on the store in parallel from other threads, while the checkpoint is being taken?

**Comment by kdprince33** [comment]
I have multiple unit tests that each create their own instance of a wrapper of the faster cache.  Each test could be executed in it's own thread due to having up to 4 test worker threads.  Could this be related?

**Comment by badrishc** [comment]
I'm wondering if the issue is with the way I interpreted the result of WriteFile on Windows here:

https://github.com/microsoft/FASTER/blob/7f4eeed57eb6e85f4b47df5c3c34ee46f44c5bca/cs/src/core/Device/LocalStorageDevice.cs#L92

The assumption I have made is that if Native32.WriteFile returns true, it means that the I/O completed synchronously and we need to manually invoke the callback here:

https://github.com/microsoft/FASTER/blob/7f4eeed57eb6e85f4b47df5c3c34ee46f44c5bca/cs/src/core/Device/LocalStorageDevice.cs#L125

However, I wonder if the behavior instead is that even with synchronous I/O, the callback would get invoked during the WriteFile, just synchronously instead of asynchronously. In that case, we would be having an extra invocation of the callback in our code above, which might be causing the issue (since we would signal the countdown event more than the number it is initialized to).

We have not encountered this issue in practice yet, because all devices we have tested against have always been asynchronous for all calls.

Can you try the following and see if it fixes the problem: comment out the line that performs the synchronous callback at https://github.com/microsoft/FASTER/blob/7f4eeed57eb6e85f4b47df5c3c34ee46f44c5bca/cs/src/core/Device/LocalStorageDevice.cs#L125

**Comment by kdprince33** [comment]
Thanks for looking into this.  I was on vacation last week but will try this out this week to see if it addresses the problem.  Unfortunately, this only happens on our build server and I'm unable to repro this locally which makes this exceedingly hard to debug.

**Comment by badrishc** [comment]
Any progress?

**Comment by kdprince33** [comment]
This fixes the issue I encountered.  I patched our code with your latest changes and now our tests are passing.  Sorry for not getting back to you sooner.
