### ISSUE TITLE
NullReferenceException on FasterKV creation

### ISSUE THREAD

**Issue by gore01** [microsoft/FASTER#137]
Hi! I'm trying to play w/faster and have started from the https://github.com/microsoft/FASTER/tree/master/cs/playground/SumStore as a reference.

I've implemented Index struct for the key part that is based on a string value. 
```
public struct Index : IFasterEqualityComparer<Index>
    {
        public string Key;

        public unsafe long GetHashCode64(ref Index k)
        {
            var keyS = k.Key.AsSpan();
            Span<byte> bytes = stackalloc byte[keyS.Length];

            var written = Encoding.ASCII.GetBytes(keyS, bytes);
            fixed (byte* pb = bytes)
            {
                return Utility.HashBytes(pb, written);
            }
        }

        public bool Equals(ref Index k1, ref Index k2)
        {
            return string.Equals(k1.Key, k2.Key, StringComparison.OrdinalIgnoreCase);
        }
    }
```

All other parts are the same.

The version of faster is 2019.4.24.4 (nuget.org)

When I try to initialize store I got a NullreferenceException in the faster ctor
```
   at FASTER.core.GenericAllocator`2..ctor(LogSettings settings, SerializerSettings`2 serializerSettings, IFasterEqualityComparer`1 comparer, Action`2 evictCallback, LightEpoch epoch) in d:\a\1\s\cs\src\core\Allocator\GenericAllocator.cs:line 64
   at FASTER.core.FasterKV`6..ctor(Int64 size, Functions functions, LogSettings logSettings, CheckpointSettings checkpointSettings, SerializerSettings`2 serializerSettings, IFasterEqualityComparer`1 comparer, VariableLengthStructSettings`2 variableLengthStructSettings) in d:\a\1\s\cs\src\core\Index\FASTER\FASTER.cs:line 161
   at PlayingWithFaster.IndexStore..ctor() in C:\src\!\PlayingWithFaster\PlayingWithFaster\IndexStore.cs:line 19
   at PlayingWithFaster.Program.Main(String[] args) in C:\src\!\PlayingWithFaster\PlayingWithFaster\Program.cs:line 9
```
To avoid such thing I must implement custom serializers for the Index and NumClicks structures and pass it through the serializerSettings parameter in a ctor.

I think there should be some kind of user friendly exception that describes why we need to implement custom serializers for the key/value part.

**Comment by badrishc** [comment]
Correct, we need custom serializers when the key or value types are not blittable structs, because otherwise we would not know how to read and write them to storage. The error check was previously only looking for class objects, we have now expanded it to check for non-blittable types.
