### ISSUE TITLE
AccessViolationException when running benchmark

### ISSUE THREAD

**Issue by ayende** [Microsoft/FASTER#15]
Clone the repo, opened the C# solution, set mode to release, run the `FASTER.benchmark` project.
(Ctrl+F5 in VS after marking it as a startup project).

I get the following output and the process die with access violation.

```
WARNING: Could not find YCSB directory, loading synthetic data instead
loaded 250000000 keys.
loaded 1000000000 txns.
loaded 1000000000 txns.
Executing setup.





Unhandled Exception: Unhandled Exception:Unhandled Exception:  Unhandled Exception: Unhandled Exception:
Unhandled Exception:
Unhandled Exception:
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at FASTER.core.FasterKV.InternalUpsert(Key* key, Value* value, Context* userContext, PendingContext& pendingContext) in C:\Work\FASTER\cs\src\core\Index\FASTER\FASTERImpl.cs:line 371
   at FASTER.benchmark.FASTER_YcsbBenchmark.SetupYcsb(Int32 thread_idx) in C:\Work\FASTER\cs\benchmark\FasterYcsbBenchmark.cs:line 132
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at FASTER.core.FasterKV.InternalUpsert(Key* key, Value* value, Context* userContext, PendingContext& pendingContext) in C:\Work\FASTER\cs\src\core\Index\FASTER\FASTERImpl.cs:line 371
   at FASTER.benchmark.FASTER_YcsbBenchmark.SetupYcsb(Int32 thread_idx) in C:\Work\FASTER\cs\benchmark\FasterYcsbBenchmark.cs:line 132
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at FASTER.core.FasterKV.InternalUpsert(Key* key, Value* value, Context* userContext, PendingContext& pendingContext) in C:\Work\FASTER\cs\src\core\Index\FASTER\FASTERImpl.cs:line 371
   at FASTER.benchmark.FASTER_YcsbBenchmark.SetupYcsb(Int32 thread_idx) in C:\Work\FASTER\cs\benchmark\FasterYcsbBenchmark.cs:line 132
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at FASTER.core.FasterKV.InternalUpsert(Key* key, Value* value, Context* userContext, PendingContext& pendingContext) in C:\Work\FASTER\cs\src\core\Index\FASTER\FASTERImpl.cs:line 371
   at FASTER.benchmark.FASTER_YcsbBenchmark.SetupYcsb(Int32 thread_idx) in C:\Work\FASTER\cs\benchmark\FasterYcsbBenchmark.cs:line 132
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at FASTER.core.FasterKV.InternalUpsert(Key* key, Value* value, Context* userContext, PendingContext& pendingContext) in C:\Work\FASTER\cs\src\core\Index\FASTER\FASTERImpl.cs:line 371
   at FASTER.benchmark.FASTER_YcsbBenchmark.SetupYcsb(Int32 thread_idx) in C:\Work\FASTER\cs\benchmark\FasterYcsbBenchmark.cs:line 132
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at FASTER.core.FasterKV.InternalUpsert(Key* key, Value* value, Context* userContext, PendingContext& pendingContext) in C:\Work\FASTER\cs\src\core\Index\FASTER\FASTERImpl.cs:line 371
   at FASTER.benchmark.FASTER_YcsbBenchmark.SetupYcsb(Int32 thread_idx) in C:\Work\FASTER\cs\benchmark\FasterYcsbBenchmark.cs:line 132
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at FASTER.core.FasterKV.InternalUpsert(Key* key, Value* value, Context* userContext, PendingContext& pendingContext) in C:\Work\FASTER\cs\src\core\Index\FASTER\FASTERImpl.cs:line 371
   at FASTER.benchmark.FASTER_YcsbBenchmark.SetupYcsb(Int32 thread_idx) in C:\Work\FASTER\cs\benchmark\FasterYcsbBenchmark.cs:line 132
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at FASTER.core.FasterKV.InternalUpsert(Key* key, Value* value, Context* userContext, PendingContext& pendingContext) in C:\Work\FASTER\cs\src\core\Index\FASTER\FASTERImpl.cs:line 371
   at FASTER.benchmark.FASTER_YcsbBenchmark.SetupYcsb(Int32 thread_idx) in C:\Work\FASTER\cs\benchmark\FasterYcsbBenchmark.cs:line 132
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

**Comment by uliian** [comment]
me too

**Comment by badrishc** [comment]
Issue was that the benchmark looks for the D: drive by default, and fails silently if the drive is not found. This is now fixed (throwing exception if the storage device is not found). Also, we set the default log device path to to C:\data\hlog and set number of threads to 1, as well as reduced the number of operations, so that the benchmark works easily out of the box on slower machines.
