### ISSUE TITLE
[C#] NullReferenceException when executing benchmarking tool w/ RMW and checkpoints

### ISSUE THREAD

**Issue by shadimari** [microsoft/FASTER#321]
When executing C# benchmarking tool with the following configurations:
reads_percent = -1 (i.e. 100% RMW)
kCheckpointMilliseconds= 10000
kRunSeconds = 60 seconds
kUseSmallData = true/false
kUseSyntheticData = true
kCheckpointStoreContents = true
kAffinitizedSession = true/false
kSmallMemoryLog = true/false

Threads exit with NullReferenceException while checkpointing from the main-thread. Basically, the error occurs during the invocation of session.CompletePending(false), and in specific this line of code in FASTERThread.cs:
ref Value value = ref pendingContext.value.Get();

StackTrace:
System.NullReferenceException: Object reference not set to an instance of an object.
   at FASTER.core.FasterKV`2.InternalCompleteRetryRequest[Input,Output,Context,FasterSession](FasterExecutionContext`3 opCtx, FasterExecutionContext`3 currentCtx, PendingContext`3 pendingContext, FasterSession fasterSession) in D:\arabyads\sandbox\FASTER\cs\src\core\Index\FASTER\FASTERThread.cs:line 217
   at FASTER.core.FasterKV`2.InternalCompleteRetryRequests[Input,Output,Context,FasterSession](FasterExecutionContext`3 opCtx, FasterExecutionContext`3 currentCtx, FasterSession fasterSession) in D:\arabyads\sandbox\FASTER\cs\src\core\Index\FASTER\FASTERThread.cs:line 204
   at FASTER.core.FasterKV`2.InternalCompletePending[Input,Output,Context,FasterSession](FasterExecutionContext`3 ctx, FasterSession fasterSession, Boolean wait) in D:\arabyads\sandbox\FASTER\cs\src\core\Index\FASTER\FASTERThread.cs:line 167
   at FASTER.core.ClientSession`6.CompletePending(Boolean spinWait, Boolean spinWaitForCommit) in D:\arabyads\sandbox\FASTER\cs\src\core\ClientSession\ClientSession.cs:line 396
   at FASTER.benchmark.FASTER_YcsbBenchmark.RunYcsb(Int32 thread_idx) in D:\arabyads\sandbox\FASTER\cs\benchmark\FasterYcsbBenchmark.cs:line 164
   at FASTER.benchmark.FASTER_YcsbBenchmark.<>c__DisplayClass29_1.<Run>b__1() in D:\arabyads\sandbox\FASTER\cs\benchmark\FasterYcsbBenchmark.cs:line 304
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by badrishc** [comment]
Thanks for the report. The linked PR fixes this issue.

**Comment by badrishc** [comment]
Also, you do not need to set `kCheckpointStoreContents` as its intention is for backup for fast future benchmark runs when running without periodic checkpoints. You only need to set `kCheckpointMilliseconds` to enable periodic checkpointing. We have updated the benchmark code with renamed variables in the PR to remove the confusion:
* `kCheckpointMilliseconds` => `kPeriodicCheckpointMilliseconds`
* `kCheckpointStoreContents` => `kBackupStoreForFastRestarts`

**Comment by shadimari** [comment]
Thanks for the update and the clarification. Issue is fixed.
