### ISSUE TITLE
Exception thrown when attempting to write entry (epoch entry reservation failure)

### ISSUE THREAD

**Issue by mnmr** [microsoft/FASTER#388]
I'm seeing quite a few of these when starting up my service using Faster (this is using 1.7.4 with the VM hotfix):

2020-12-15 15:43:50.647 [FTL] HistoryActor-84616 => Caught and swallowed unhandled FasterException
FASTER.core.FasterException: Unable to reserve an epoch entry, try increasing the epoch table size (kTableSize)
   at FASTER.core.LightEpoch.ReserveEntry(Int32 startIndex, Int32 threadId)
   at FASTER.core.LightEpoch.ReserveEntryForThread()
   at FASTER.core.FasterLog.TryEnqueue(Byte[] entry, Int64& logicalAddress)
   at FASTER.core.FasterLog.EnqueueAsync(Byte[] entry, CancellationToken token)
   at RF.History.Core.Storage.Core.FasterStore`1.WriteAsync(T item)

As far as I can tell the kTableSize is a const value, so not something I can tweak. Any ideas as to why this might be happening?

**Comment by mnmr** [comment]
I have upgraded to 1.8.0 (and set the LocalStorageDevice.UsePrvileges to false), and am no longer seeing the exception, so am closing this again.
