### ISSUE TITLE
[C#] Unhandled exception when try to recover

### ISSUE THREAD

**Issue by EugeneZhudro** [microsoft/FASTER#617]
Sometimes I get an unhandled exception when calling Recover() method of  FasterKV<Key, Value> class

System.Runtime.Serialization.SerializationException
  HResult=0x8013150C
  Message=Expecting element 'ArrayOfstring' from namespace 'http://schemas.microsoft.com/2003/10/Serialization/Arrays'.. Encountered 'None'  with name '', namespace ''.
  Source=System.Private.DataContractSerialization
  StackTrace:
   at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at FASTER.core.DataContractObjectSerializer`1.Deserialize(T& obj)
   at FASTER.core.GenericAllocator`2.Deserialize(Byte* raw, Int64 ptr, Int64 untilptr, Record`2[] src, Stream stream)
   at FASTER.core.GenericAllocator`2.AsyncReadPageWithObjectsCallback[TContext](UInt32 errorCode, UInt32 numBytes, Object context)
   at FASTER.core.LocalStorageDevice.ReadAsync(Int32 segmentId, UInt64 sourceAddress, IntPtr destinationAddress, UInt32 readLength, DeviceIOCompletionCallback callback, Object context)
   at FASTER.core.GenericAllocator`2.AsyncReadPageWithObjectsCallback[TContext](UInt32 errorCode, UInt32 numBytes, Object context)
   at FASTER.core.LocalStorageDevice._callback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)

**Comment by badrishc** [comment]
Looks like an issue with your serialization or deserialization code. See if it can be repro'ed with a simple correct serializer such as the one in our [samples](https://github.com/microsoft/FASTER/blob/master/cs/samples/StoreCustomTypes/Types.cs), to confirm.

If not,  a stand alone repro would help us quickly diagnose and fix of there is indeed a problem on our side.  Thanks.

**Comment by EugeneZhudro** [comment]
I don't use any custom serialization or deserialization code. The issue happened when the application stop before files was be saved. Then I try to recover and get an unhandled exception (can't catch it) and my application stopped

Example:
https://github.com/EugeneZhudro/Faster.RecoverIssue

Broken files:
https://drive.google.com/file/d/1zuVM05KqZ5o7pv39Dg8NPzP-k4gYBwC4/view?usp=sharing

Thanks

**Comment by badrishc** [comment]
Thanks for the repro. Could you try the fix in the linked PR https://github.com/microsoft/FASTER/pull/619 and let us know if it resolves the issue? If not, it would be useful to get the code that creates the object log in the first place, not just the recovery code path.

**Comment by EugeneZhudro** [comment]
No, it doesn't resolve. I added to repro method how we create object log. The main problem we cannot catch an exception (for example for recreating log). We can only catch this exception using onlyAppDomain.CurrentDomain.UnhandledException, it looks very strange

**Comment by badrishc** [comment]
I see the `TrySave` method but it is not called in your repro.

**Comment by badrishc** [comment]
With the linked PR, you have to recreate the data and take a fresh checkpoint. It will not resolve the issue for existing checkpoint. The issue was with how we serialize the data initially, not how we recover.

**Comment by EugeneZhudro** [comment]
Thanks, We will try using this fix in our product. Anyway I think exception which client cannot catch in try catch block is not good

**Comment by badrishc** [comment]
Thanks for the feedback. Agreed, we will look into how to surface serialization exceptions to end user cleanly. CC @TedHartMS
