### ISSUE TITLE
Exception occured in iterating FasterLog with FastCommitMode=true

### ISSUE THREAD

**Issue by itn3000** [microsoft/FASTER#691]
I tested fast commit scenario on v2, and I got following problem.

# Environment

* dotnet-6.0
* Windows10 x64
* Microsoft.FASTER.Core 2.0.0

# Steps to reproduce

1. create new console project
2. add FasterLog-2.0.0 to project
3. run https://gist.github.com/itn3000/9452a468f5e5e2da8b339dc40fd6e5df code

# Expected Result

output only "100, 25600"(this is total iterating num and total read byte length)

# Actual Result

get following output

```
error in scan:FASTER.core.FasterException: Invalid version found during commit recovery
   at FASTER.core.FasterLogRecoveryInfo.Initialize(BinaryReader reader)
   at FASTER.core.FasterLogScanIterator.GetNext(Byte[]& entry, Int32& entryLength, Int64& currentAddress, Int64& nextAddress)
   at FASTER.core.FasterLogScanIterator.GetAsyncEnumerable(CancellationToken token)+MoveNext()
   at FASTER.core.FasterLogScanIterator.GetAsyncEnumerable(CancellationToken token)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Program.<Main>$(String[] args) in D:\src\gitrepos\dotnet-sandbox\fasterlabs2\flprev2\Program.cs:line 30
   at Program.<Main>$(String[] args) in D:\src\gitrepos\dotnet-sandbox\fasterlabs2\flprev2\Program.cs:line 30
100, 25600
```

**Comment by badrishc** [comment]
Fixed in linked PR.
