### ISSUE TITLE
Process terminated. Assertion failed. Should always retrieve a non-Tentative, non-Sealed record from disk

### ISSUE THREAD

**Issue by cmadh** [microsoft/FASTER#779]
For a couple of Days (since I added some new Code, playing around with a possible implemenentation for SIs) my Application was Segfaulting without obvious reason, sometimes in .NET BGC, sometimes .NET Server GC. 

Trying to find the root of the Issue, analyzing coredumps with lldb etc. didn't give me information allowing to fix the issue.

ClrStack: 

    (lldb) clrstack -r
    OS Thread Id: 0x1ddb1e (1)
            Child SP               IP Call Site
    00007FFE92ABC5D0 00007f0318050376 [HelperMethodFrame_1OBJ: 00007ffe92abc5d0] System.Threading.Monitor.ObjWait(Int32, System.Object)
        rsp=00007ffe92abbf70 rbp=0000559dbccb6508 rip=00007f0318050376
        rax=fffffffffffffe00 rbx=0000000000000000 rcx=00007f0318050376
        rdx=0000000000000000 rsi=0000000000000080 rdi=0000559dbccb6530
         r8=0000000000000000  r9=0000000000000000 r10=0000000000000000
        r11=0000000000000282 r12=0000559dbccb652c r13=0000559dbccb64e0
        r14=00007ffe92abbfb0 r15=0000559dbccb6530
    00007FFE92ABC700 00007F0298638237 System.Threading.ManualResetEventSlim.Wait(Int32, System.Threading.CancellationToken) [/_/src/libraries/System.Private.CoreLib/src/System/Threading/ManualResetEventSlim.cs @ 575]
        rsp=00007ffe92abc700 rbp=00007ffe92abc770 rip=00007f0298638237
        rax=fffffffffffffe00 rbx=00000000ffffffff rcx=00007f0318050376
        rdx=0000000000000000 rsi=0000000000000080 rdi=0000559dbccb6530
         r8=0000000000000000  r9=0000000000000000 r10=0000000000000000
        r11=0000000000000282 r12=00000000ffffffff r13=0000000000000000
        r14=0000000000000000 r15=0000000000000000
    00007FFE92ABC780 00007F029864D6C1 System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, System.Threading.CancellationToken) [/_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs @ 3021]
        rsp=00007ffe92abc780 rbp=00007ffe92abc7d0 rip=00007f029864d6c1
        rax=fffffffffffffe00 rbx=00000000ffffffff rcx=00007f0318050376
        rdx=0000000000000000 rsi=0000000000000080 rdi=0000559dbccb6530
         r8=0000000000000000  r9=0000000000000000 r10=0000000000000000
        r11=0000000000000282 r12=0000000000000000 r13=00007ec288c6c378
        r14=0000000000000000 r15=0000000000000001
    00007FFE92ABC7E0 00007F029864D4A9 System.Threading.Tasks.Task.InternalWaitCore(Int32, System.Threading.CancellationToken) [/_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs @ 2956]
        rsp=00007ffe92abc7e0 rbp=00007ffe92abc820 rip=00007f029864d4a9
        rax=fffffffffffffe00 rbx=00007ec2861be988 rcx=00007f0318050376
        rdx=0000000000000000 rsi=0000000000000080 rdi=0000559dbccb6530
         r8=0000000000000000  r9=0000000000000000 r10=0000000000000000
        r11=0000000000000282 r12=00007ec2860fa1f8 r13=0000000000000000
        r14=00000000ffffffff r15=0000000000000000
    00007FFE92ABC830 00007F029869C954 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) [/_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs @ 140]
        rsp=00007ffe92abc830 rbp=00007ffe92abc840 rip=00007f029869c954
        rax=fffffffffffffe00 rbx=00007ec2861be988 rcx=00007f0318050376
        rdx=0000000000000000 rsi=0000000000000080 rdi=0000559dbccb6530
         r8=0000000000000000  r9=0000000000000000 r10=0000000000000000
        r11=0000000000000282 r12=00007ffe92abcb58 r13=0000000000000000
        r14=0000000000000000 r15=00007ffe92abcbe0
    00007FFE92ABC850 00007F0299070AEC Program.<Main>(System.String[])
        rsp=00007ffe92abc850 rbp=00007ffe92abc870 rip=00007f0299070aec
        rax=fffffffffffffe00 rbx=00007ffe92abca00 rcx=00007f0318050376
        rdx=0000000000000000 rsi=0000000000000080 rdi=0000559dbccb6530
         r8=0000000000000000  r9=0000000000000000 r10=0000000000000000
        r11=0000000000000282 r12=00007ffe92abcb58 r13=0000000000000000
        r14=0000000000000000 r15=00007ffe92abcbe0
    (lldb)

(ip2md and others don't give any results here)

verifyheap and objdump:

    (lldb) verifyheap
    Object 00007ec28630bc00: Bad member 00007EC200000018 at 00007EC28630CBC0.
    
    Last good object: 00007EC28630BBA0.
    (lldb) dumpobj 00007ec28630bc00
    Name:        FASTER.core.Record`2[[DeepReader.Storage.Faster.SecondaryIndices.Faster.NameIndex.ISecondaryIndexKey, DeepReader.Storage],[DeepReader.Storage.Faster.SecondaryIndices.Faster.NameNameIndex.ISecondaryIndexValue, DeepReader.Storage]][]
    MethodTable: 00007f029c1095e0
    EEClass:     00007f029c109558
    Tracked Type: false
    Size:        4128(0x1020) bytes
    Array:       Rank 1, Number of elements 171, Type VALUETYPE
    Fields:
    None

Today I turned of Concurrent GC, Server GC and GC CPU Affinitization in the runtimeconfig.json

    "configProperties": {
      "System.GC.Concurrent": false,
      "System.GC.Server": false,
      "System.GC.NoAffinitize": true,
    }

and suddenly I'm getting

     Process terminated. Assertion failed.
        Should always retrieve a non-Tentative, non-Sealed record from disk
           at FASTER.core.FasterKV`2.InternalContinuePendingRMW[Input,Output,Context,FasterSession](FasterExecutionContext`3 opCtx, AsyncIOContext`2 request, PendingContext`3& pendingContext, FasterSession fasterSession, FasterExecutionContext`3 sessionCtx)
           at FASTER.core.FasterKV`2.InternalCompletePendingRequestFromContext[Input,Output,Context,FasterSession](FasterExecutionContext`3 opCtx, FasterExecutionContext`3 currentCtx, FasterSession fasterSession, AsyncIOContext`2 request, PendingContext`3& pendingContext, AsyncIOContext`2& newRequest)
           at FASTER.core.FasterKV`2.InternalCompletePendingRequest[Input,Output,Context,FasterSession](FasterExecutionContext`3 opCtx, FasterExecutionContext`3 currentCtx, FasterSession fasterSession, AsyncIOContext`2 request, CompletedOutputIterator`5 completedOutputs)
           at FASTER.core.FasterKV`2.InternalCompletePendingRequests[Input,Output,Context,FasterSession](FasterExecutionContext`3 opCtx, FasterExecutionContext`3 currentCtx, FasterSession fasterSession, CompletedOutputIterator`5 completedOutputs)
           at FASTER.core.FasterKV`2.InternalCompletePending[Input,Output,Context,FasterSession](FasterExecutionContext`3 ctx, FasterSession fasterSession, Boolean wait, CompletedOutputIterator`5 completedOutputs)
           at FASTER.core.ClientSession`6.UnsafeCompletePending[FasterSession](FasterSession fasterSession, Boolean getOutputs, Boolean wait, Boolean spinWaitForCommit)
           at FASTER.core.ClientSession`6.CompletePending(Boolean getOutputs, Boolean wait, Boolean spinWaitForCommit)
           at FASTER.core.ClientSession`6.CompletePending(Boolean wait, Boolean spinWaitForCommit)
           at DeepReader.Storage.Faster.SecondaryIndices.Faster.Store.SecondaryIndexStore.StartNameNameIndexer(ChannelReader`1 reader, CancellationToken token, String indexName, SecondaryIndex indexType) in E:\source\repos\DeepReader\DeepReader.Storage\Faster\SecondaryIndices\Faster\Store\SecondaryIndexStore.cs:line 386
           at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
           at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
           at System.Threading.Channels.ChannelReader`1.ReadAllAsync(CancellationToken cancellationToken)+MoveNext()
           at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
           at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
           at System.Threading.ThreadPoolWorkQueue.Dispatch()
           at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

instead.

I tried to build a minimal reproducible example but so far no chance. 

I'm basically performing a lot or RMWs on RezisableLists of primitives, if the List is full, I clone the List and upsert it with a new Key while upserting an empty List with the old Key to replace it (calling session.CompletePending(true) after each RMW or Upsert). It runs fine for some time and depending on the load the Segfault happens or the Assertion fails after some time. 

As I saw some changes in [locktable-completepending](https://github.com/microsoft/FASTER/tree/locktable-completepending) after I submitted the last Issue, in addition to the latest release I tried running my Application using the locktable-completepending-branch, with the same result.

**Comment by cmadh** [comment]
I've uploaded a coredump here: [Faster Segfault Coredump](https://drive.google.com/drive/folders/1-K3eqJTOQqJXuWKDIUoyrWg2ua7tSOJs?usp=share_link)

**Comment by badrishc** [comment]
Are you using the lockable context (manual locking) feature? We are currently reworking the design due to stability issues with the "automatic lock transfer" feature. If this might be the cause, you want wait a week for the updated simpler locking strategy.

**Comment by badrishc** [comment]
Let us know if the latest in https://github.com/microsoft/FASTER/pull/783 works for you. If not, a repro would be needed to make forward progress here. Thanks.
